{% set name = "spectoprep" %}
{% set version = "0.1.0" %}  # This will be updated by the workflow

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0000000000000000000000000000000000000000000000000000000000000000  # This will be updated by the workflow

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0.0
    - wheel
  run:
    - python >=3.9
    # Add your runtime dependencies here

test:
  imports:
    - spectoprep
  commands:
    - python -c "import spectoprep; print(spectoprep.__version__)"

about:
  home: https://github.com/habeeb3579/spectoprep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Short description of your package'
  description: |
    Longer description of your package that can
    span multiple lines if needed.
  doc_url: https://habeeb3579.github.io/spectoprep/
  dev_url: https://github.com/habeeb3579/spectoprep

extra:
  recipe-maintainers:
    - habeeb3579