name: 📚 General Question
description: Ask a question or request help
title: "[QUESTION]: "
labels: ["question"]
assignees:
  - habeeb3579
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to ask a question!
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I use this feature?
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Question Area
      description: What area does your question relate to?
      options:
        - Installation
        - Configuration
        - Usage
        - Development
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about your question
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true