{% set name = "spectoprep" %}
{% set pypi_name = "spectoprep" %}
{% set data = load_setup_py_data() %}
{% set version = data.get('version') or "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..  # Points to the repository root

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9
    - typer
    - bayesian-optimization
    - seaborn

test:
  imports:
    - spectoprep
  commands:
    - python -c "import spectoprep; print(spectoprep.__version__)"

about:
  home: https://github.com/habeeb3579/spectoprep
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A comprehensive spectral preprocessing toolkit for chemometrics.
  description: |
    Spectoprep is a comprehensive spectral preprocessing toolkit supporting major workflows for chemometric pipelines.
  doc_url: https://github.com/habeeb3579/spectoprep
  dev_url: https://github.com/habeeb3579/spectoprep

extra:
  recipe-maintainers:
    - habeeb3579